<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\idle.gif" />
    <None Remove="Assets\talk.gif" />
    <None Remove="Assets\walk.gif" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.CognitoIdentityProvider" Version="4.0.8.8" />
    <PackageReference Include="AWSSDK.Core" Version="4.0.7.4" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.18.6" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.23.5" />
    <PackageReference Include="AWSSDK.TranscribeService" Version="4.0.6.2" />
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\idle.gif" />
    <Resource Include="Assets\talk.gif" />
    <Resource Include="Assets\walk.gif" />
  </ItemGroup>

</Project>
